# Generated by Django 3.2.25 on 2024-12-06 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppDesign', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advuser',
            name='full_name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='advuser',
            name='login',
            field=models.CharField(max_length=150, null=True, unique=True),
        ),
    ]
