# Generated by Django 3.2.25 on 2024-12-06 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppDesign', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advuser',
            name='has_logged_in',
            field=models.BooleanField(default=False),
        ),
    ]
