# Generated by Django 5.1.4 on 2024-12-08 12:41

import AppDesign.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppDesign', '0002_advuser_has_logged_in'),
    ]

    operations = [
        migrations.CreateModel(
            name='InteriorDesignRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название заявки')),
                ('email', models.EmailField(max_length=254, verbose_name='Ваш email')),
                ('phone', models.CharField(max_length=15, verbose_name='Ваш телефон')),
                ('project_description', models.TextField(verbose_name='Описание заявки')),
                ('design_image', models.ImageField(upload_to='design_images/', validators=[AppDesign.models.validate_image], verbose_name='Фото помещения')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Новая', max_length=20)),
            ],
        ),
    ]
