# Generated by Django 5.1.4 on 2024-12-08 13:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppDesign', '0003_interiordesignrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='interiordesignrequest',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
