# Generated by Django 5.1.3 on 2024-12-09 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppDesign', '0006_auto_20241209_1139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advuser',
            name='has_logged_in',
        ),
        migrations.AddField(
            model_name='advuser',
            name='status',
            field=models.CharField(choices=[('offline', 'Не живой'), ('online', 'Живой')], default='offline', max_length=10),
        ),
    ]
